-- Migration 0029 — Social schema (Session G.1)
-- Date: 2026-04-26
-- Author: Claude (platform Session 10) with owner sign-off
-- Reason: Multi-brand organic social automation. Drafts, engagement targets, OAuth
--         tokens, post analytics. Designed multi-brand (SwitchLeads + Switchable) and
--         multi-channel (LinkedIn personal/company, Meta facebook/instagram, TikTok)
--         from day one — `(brand, channel)` is the unique posting surface key.
--
--         OAuth tokens are encrypted at rest via Supabase Vault (pgsodium-backed):
--         we enable the extension, then store ciphertext in `vault.secrets` with a
--         UUID reference column on `social.oauth_tokens`. Admin UI never surfaces
--         raw tokens; Edge Functions read decrypted via `vault.decrypted_secrets`.
--
--         Build sequencing, UI page list, OAuth flow detail, Edge Function inventory,
--         push-notification implementation, and future-extensibility notes live in
--         `platform/docs/admin-dashboard-scoping.md` § Session G — this migration
--         implements only what `platform/docs/data-architecture.md` § "Schema: social"
--         describes.
--
--         RLS posture: admin only at this stage. Every table has RLS enabled with
--         deny-all-by-default; explicit policies grant SELECT + write to authenticated
--         admin users via `admin.is_admin()` (the existing helper from migration 0014).
--         Phase 4 may extend specific tables for provider-facing access; not in scope.
--
-- Related: platform/docs/data-architecture.md § "Schema: social",
--          platform/docs/admin-dashboard-scoping.md § Session G,
--          platform/supabase/migrations/0014_admin_dashboard_read_access.sql (admin.is_admin()),
--          platform/supabase/migrations/0019_vault_helper_for_shared_secrets.sql (Vault precedent).

-- UP

-- =============================================================================
-- 0. Extensions + schema
-- =============================================================================

-- pgsodium provides the cryptographic primitives Supabase Vault sits on top of.
-- The `vault` schema (with `vault.secrets` + `vault.decrypted_secrets` view) is
-- created automatically by Supabase when pgsodium is enabled.
CREATE EXTENSION IF NOT EXISTS pgsodium;

-- pgcrypto powers gen_random_uuid() — already enabled in earlier migrations on
-- this Supabase project, but defensive enable here for portability/local dev.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS social;

GRANT USAGE ON SCHEMA social TO authenticated;

-- =============================================================================
-- 1. social.drafts
-- =============================================================================

CREATE TABLE social.drafts (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  brand                       TEXT NOT NULL,
  channel                     TEXT NOT NULL,
  scheduled_for               TIMESTAMPTZ,
  status                      TEXT NOT NULL DEFAULT 'pending',
  content                     TEXT NOT NULL,
  pillar                      TEXT,
  hook_type                   TEXT,
  cron_batch_id               UUID,
  approved_by                 UUID REFERENCES auth.users(id),
  approved_at                 TIMESTAMPTZ,
  edit_history                JSONB,
  rejection_reason_category   TEXT,
  rejection_reason            TEXT,
  external_post_id            TEXT,
  published_at                TIMESTAMPTZ,
  publish_error               TEXT,
  schema_version              TEXT NOT NULL DEFAULT '1.0',
  CONSTRAINT social_drafts_brand_chk
    CHECK (brand IN ('switchleads', 'switchable')),
  CONSTRAINT social_drafts_channel_chk
    CHECK (channel IN ('linkedin_personal', 'linkedin_company', 'meta_facebook', 'meta_instagram', 'tiktok')),
  CONSTRAINT social_drafts_status_chk
    CHECK (status IN ('pending', 'approved', 'rejected', 'published', 'failed')),
  CONSTRAINT social_drafts_rejection_reason_required_chk
    CHECK (status <> 'rejected' OR rejection_reason_category IS NOT NULL),
  CONSTRAINT social_drafts_rejection_category_chk
    CHECK (rejection_reason_category IS NULL
           OR rejection_reason_category IN ('voice', 'topic_off', 'factual_wrong', 'duplicate', 'timing', 'other'))
);

CREATE INDEX social_drafts_brand_channel_status_idx
  ON social.drafts (brand, channel, status);
CREATE INDEX social_drafts_approved_scheduled_idx
  ON social.drafts (status, scheduled_for) WHERE status = 'approved';

COMMENT ON TABLE social.drafts IS
  'Content drafts in the review pipeline. Cron-generated by social-draft-generate (Mon + Thu); reviewed in /social/drafts; published by social-publish cron when status=approved AND scheduled_for <= now(). Multi-brand, multi-channel from day one.';

-- =============================================================================
-- 2. social.engagement_targets
-- =============================================================================

CREATE TABLE social.engagement_targets (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  added_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  brand                    TEXT NOT NULL,
  channel                  TEXT NOT NULL DEFAULT 'linkedin_personal',
  name                     TEXT NOT NULL,
  company                  TEXT,
  title                    TEXT,
  profile_url              TEXT NOT NULL,
  why_target               TEXT,
  posting_cadence_estimate TEXT,
  last_engaged_at          TIMESTAMPTZ,
  last_followed_back_at    TIMESTAMPTZ,
  status                   TEXT NOT NULL DEFAULT 'active',
  source                   TEXT,
  last_reviewed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  notes                    TEXT,
  CONSTRAINT social_targets_brand_chk
    CHECK (brand IN ('switchleads', 'switchable')),
  CONSTRAINT social_targets_channel_chk
    CHECK (channel IN ('linkedin_personal', 'linkedin_company', 'meta_facebook', 'meta_instagram', 'tiktok')),
  CONSTRAINT social_targets_status_chk
    CHECK (status IN ('active', 'retired', 'paused')),
  CONSTRAINT social_targets_brand_profile_uniq
    UNIQUE (brand, profile_url)
);

CREATE INDEX social_targets_brand_status_idx
  ON social.engagement_targets (brand, status);

COMMENT ON TABLE social.engagement_targets IS
  'Curated list of accounts to engage with. Brand = whose audience we are reaching via this engagement. Same person can legitimately be a target for both brands. last_reviewed_at drives the quarterly review trigger via vw_targets_due_review.';

-- =============================================================================
-- 3. social.engagement_queue
-- =============================================================================

CREATE TABLE social.engagement_queue (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  target_id            UUID NOT NULL REFERENCES social.engagement_targets(id) ON DELETE CASCADE,
  post_url             TEXT NOT NULL,
  post_preview         TEXT,
  detected_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  drafted_comment      TEXT,
  status               TEXT NOT NULL DEFAULT 'pending',
  commented_at         TIMESTAMPTZ,
  notification_sent_at TIMESTAMPTZ,
  expires_at           TIMESTAMPTZ,
  CONSTRAINT social_queue_status_chk
    CHECK (status IN ('pending', 'commented', 'dismissed', 'expired'))
);

CREATE INDEX social_queue_status_detected_idx
  ON social.engagement_queue (status, detected_at);

COMMENT ON TABLE social.engagement_queue IS
  'Specific posts to comment on this week. Populated by social-engagement-ingest Edge Function from forwarded LinkedIn notification emails. Brand inferred via JOIN to engagement_targets. Auto-expires 48h after detected_at.';

-- =============================================================================
-- 4. social.post_analytics
-- =============================================================================

CREATE TABLE social.post_analytics (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_id        UUID NOT NULL REFERENCES social.drafts(id) ON DELETE CASCADE,
  captured_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  impressions     INT,
  reactions       INT,
  comments        INT,
  shares          INT,
  clicks          INT,
  follower_count  INT
);

CREATE INDEX social_analytics_draft_captured_idx
  ON social.post_analytics (draft_id, captured_at DESC);

COMMENT ON TABLE social.post_analytics IS
  'Time-series performance per published post. social-analytics-sync runs daily and pulls metrics for posts <30 days old. Brand inferred via JOIN to drafts.';

-- =============================================================================
-- 5. social.engagement_log
-- =============================================================================

CREATE TABLE social.engagement_log (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  draft_id        UUID REFERENCES social.drafts(id) ON DELETE SET NULL,
  brand           TEXT NOT NULL,
  engager_name    TEXT NOT NULL,
  engager_company TEXT,
  engager_title   TEXT,
  engagement_type TEXT,
  is_icp          BOOLEAN NOT NULL DEFAULT false,
  notes           TEXT,
  tagged_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  tagged_by       UUID REFERENCES auth.users(id),
  CONSTRAINT social_log_brand_chk
    CHECK (brand IN ('switchleads', 'switchable')),
  CONSTRAINT social_log_engagement_type_chk
    CHECK (engagement_type IS NULL
           OR engagement_type IN ('comment', 'reaction', 'share', 'profile_view'))
);

CREATE INDEX social_log_brand_icp_idx
  ON social.engagement_log (brand, is_icp);

COMMENT ON TABLE social.engagement_log IS
  'Manual ICP tagging of engagers (until volume justifies automation). brand denormalised here for easier filtering — set on insert from the joined drafts row.';

-- =============================================================================
-- 6. social.oauth_tokens
-- =============================================================================
--
-- Tokens themselves live encrypted in vault.secrets. This table holds metadata +
-- a UUID reference (access_token_secret_id, refresh_token_secret_id) to the
-- vault row. The OAuth callback route calls vault.create_secret() with the
-- raw token at insert time and stores the returned UUID here. Edge Functions
-- read the decrypted value via the vault.decrypted_secrets view; admin UI
-- never surfaces raw tokens.

CREATE TABLE social.oauth_tokens (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand                    TEXT NOT NULL,
  channel                  TEXT NOT NULL,
  provider                 TEXT NOT NULL,
  external_account_id      TEXT,
  access_token_secret_id   UUID NOT NULL,
  refresh_token_secret_id  UUID,
  expires_at               TIMESTAMPTZ,
  scopes                   TEXT[],
  last_refreshed_at        TIMESTAMPTZ,
  authorised_by            UUID REFERENCES auth.users(id),
  authorised_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT social_oauth_brand_chk
    CHECK (brand IN ('switchleads', 'switchable')),
  CONSTRAINT social_oauth_channel_chk
    CHECK (channel IN ('linkedin_personal', 'linkedin_company', 'meta_facebook', 'meta_instagram', 'tiktok')),
  CONSTRAINT social_oauth_provider_chk
    CHECK (provider IN ('linkedin', 'meta', 'tiktok')),
  CONSTRAINT social_oauth_brand_channel_uniq
    UNIQUE (brand, channel)
);

COMMENT ON TABLE social.oauth_tokens IS
  'Per-(brand, channel) OAuth metadata. access_token_secret_id and refresh_token_secret_id reference vault.secrets rows where the actual ciphertext lives. (brand, channel) is the unique posting surface key. Charlotte''s personal LinkedIn token can be reused across brands by inserting a second row pointing to the same vault secret.';

-- =============================================================================
-- 7. social.push_subscriptions
-- =============================================================================

CREATE TABLE social.push_subscriptions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint     TEXT NOT NULL,
  keys_p256dh  TEXT NOT NULL,
  keys_auth    TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT social_push_user_endpoint_uniq
    UNIQUE (user_id, endpoint)
);

COMMENT ON TABLE social.push_subscriptions IS
  'Web Push subscriptions per admin user. Used by social-engagement-ingest to send notifications when a target posts. Cascade-delete on user removal.';

-- =============================================================================
-- 8. Views
-- =============================================================================

CREATE VIEW social.vw_pending_drafts AS
  SELECT * FROM social.drafts
   WHERE status = 'pending'
   ORDER BY brand, scheduled_for NULLS LAST;

COMMENT ON VIEW social.vw_pending_drafts IS
  'Drafts awaiting review, brand-grouped, oldest-scheduled first. Drives /social/drafts.';

CREATE VIEW social.vw_post_performance AS
  SELECT d.id, d.brand, d.channel, d.pillar, d.content, d.published_at,
         MAX(pa.impressions)                          AS latest_impressions,
         MAX(pa.reactions + pa.comments + pa.shares)  AS latest_engagement
    FROM social.drafts d
    LEFT JOIN social.post_analytics pa ON pa.draft_id = d.id
   WHERE d.status = 'published'
   GROUP BY d.id;

COMMENT ON VIEW social.vw_post_performance IS
  'Per-post latest performance snapshot. Drives /social/published and feeds Thea''s Monday performance review.';

CREATE VIEW social.vw_engagement_queue_active AS
  SELECT q.id, q.post_url, q.post_preview, q.drafted_comment, q.detected_at,
         t.brand, t.name AS target_name, t.company AS target_company,
         t.profile_url AS target_profile_url
    FROM social.engagement_queue q
    JOIN social.engagement_targets t ON t.id = q.target_id
   WHERE q.status = 'pending' AND q.expires_at > now()
   ORDER BY q.detected_at DESC;

COMMENT ON VIEW social.vw_engagement_queue_active IS
  'Live engagement queue (not commented, not expired). Drives /social/queue (mobile-first).';

CREATE VIEW social.vw_targets_due_review AS
  SELECT * FROM social.engagement_targets
   WHERE status = 'active'
     AND last_reviewed_at < now() - INTERVAL '90 days';

COMMENT ON VIEW social.vw_targets_due_review IS
  'Engagement targets due quarterly review. Drives the /social/targets badge and the social-targets-quarterly-flag cron.';

CREATE VIEW social.vw_rejection_patterns AS
  SELECT brand, rejection_reason_category, COUNT(*) AS reject_count,
         DATE_TRUNC('week', updated_at) AS week
    FROM social.drafts
   WHERE status = 'rejected'
   GROUP BY brand, rejection_reason_category, week
   ORDER BY week DESC, reject_count DESC;

COMMENT ON VIEW social.vw_rejection_patterns IS
  'Reject-reason rollup by week. Feeds the next social-draft-generate cycle so the prompt adjusts for recurring rejection categories.';

CREATE VIEW social.vw_channel_status AS
  SELECT brand, channel, provider, external_account_id, expires_at,
         CASE
           WHEN expires_at IS NULL                            THEN 'no_expiry'
           WHEN expires_at > now() + INTERVAL '7 days'        THEN 'healthy'
           WHEN expires_at > now()                            THEN 'expiring_soon'
           ELSE 'expired'
         END AS health_status
    FROM social.oauth_tokens
   ORDER BY brand, channel;

COMMENT ON VIEW social.vw_channel_status IS
  'Per-(brand, channel) OAuth token health. Drives the /social/settings health badges and surfaces tokens needing reconnect.';

-- =============================================================================
-- 9. RLS — admin only at this stage
-- =============================================================================
-- Every table: RLS enabled, deny-all default, explicit admin policies for SELECT
-- + INSERT + UPDATE + DELETE via admin.is_admin(). Phase 4 may extend specific
-- tables for provider-facing access; not in scope here.

ALTER TABLE social.drafts                ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.engagement_targets    ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.engagement_queue      ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.post_analytics        ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.engagement_log        ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.oauth_tokens          ENABLE ROW LEVEL SECURITY;
ALTER TABLE social.push_subscriptions    ENABLE ROW LEVEL SECURITY;

-- Helper: a single ALL policy per table covering SELECT/INSERT/UPDATE/DELETE
-- gated by admin.is_admin(). Mirrors the per-action style from migration 0014
-- but compressed because every action requires the same gate at this stage.

CREATE POLICY admin_all_drafts ON social.drafts
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

CREATE POLICY admin_all_engagement_targets ON social.engagement_targets
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

CREATE POLICY admin_all_engagement_queue ON social.engagement_queue
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

CREATE POLICY admin_all_post_analytics ON social.post_analytics
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

CREATE POLICY admin_all_engagement_log ON social.engagement_log
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

CREATE POLICY admin_all_oauth_tokens ON social.oauth_tokens
  FOR ALL TO authenticated
  USING (admin.is_admin())
  WITH CHECK (admin.is_admin());

-- push_subscriptions is per-user — an admin should only see/manage their own
-- subscriptions. Same gate (admin only) plus a row-level user_id match.
CREATE POLICY admin_own_push_subscriptions ON social.push_subscriptions
  FOR ALL TO authenticated
  USING (admin.is_admin() AND user_id = auth.uid())
  WITH CHECK (admin.is_admin() AND user_id = auth.uid());

-- Table-level grants. RLS policies above filter rows; without these grants
-- Postgres rejects the query before RLS runs.
GRANT SELECT, INSERT, UPDATE, DELETE ON social.drafts             TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.engagement_targets TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.engagement_queue   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.post_analytics     TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.engagement_log     TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.oauth_tokens       TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON social.push_subscriptions TO authenticated;

-- =============================================================================
-- 10. Migration summary
-- =============================================================================

DO $$
DECLARE
  v_table_count INT;
  v_view_count  INT;
  v_policy_count INT;
BEGIN
  SELECT COUNT(*) INTO v_table_count
    FROM information_schema.tables
   WHERE table_schema = 'social' AND table_type = 'BASE TABLE';
  SELECT COUNT(*) INTO v_view_count
    FROM information_schema.views
   WHERE table_schema = 'social';
  SELECT COUNT(*) INTO v_policy_count
    FROM pg_policies
   WHERE schemaname = 'social';
  RAISE NOTICE 'social schema created: % tables, % views, % RLS policies',
    v_table_count, v_view_count, v_policy_count;
END $$;

-- DOWN
-- -- Destructive: drops the entire social namespace including any data inserted
-- -- after migration. Restore from a pre-migration backup if data preservation
-- -- is required.
-- --
-- -- DROP VIEW IF EXISTS social.vw_channel_status;
-- -- DROP VIEW IF EXISTS social.vw_rejection_patterns;
-- -- DROP VIEW IF EXISTS social.vw_targets_due_review;
-- -- DROP VIEW IF EXISTS social.vw_engagement_queue_active;
-- -- DROP VIEW IF EXISTS social.vw_post_performance;
-- -- DROP VIEW IF EXISTS social.vw_pending_drafts;
-- -- DROP TABLE IF EXISTS social.push_subscriptions;
-- -- DROP TABLE IF EXISTS social.oauth_tokens;
-- -- DROP TABLE IF EXISTS social.engagement_log;
-- -- DROP TABLE IF EXISTS social.post_analytics;
-- -- DROP TABLE IF EXISTS social.engagement_queue;
-- -- DROP TABLE IF EXISTS social.engagement_targets;
-- -- DROP TABLE IF EXISTS social.drafts;
-- -- REVOKE USAGE ON SCHEMA social FROM authenticated;
-- -- DROP SCHEMA IF EXISTS social;
-- -- (pgsodium + pgcrypto extensions left enabled — other schemas may rely on them.)
