-- Migration 0162 — page_views session_id column + RPC v2 for unique-session aggregation
-- Date:   2026-05-23
-- Author: Claude (Mable session, cross-project to platform) with owner sign-off
-- Reason:
--   /admin/experiments CVR column was misleading: ads_switchable.page_views logs
--   one row per page LOAD, not per visitor. Refreshes, back-button revisits,
--   internal navigation, link-preview crawlers and the owner's QA testing all
--   inflate the denominator, dragging the apparent conversion rate well below
--   reality. SMM-tees showed ~4400 loads vs 1510 Meta link clicks vs 32 form
--   submissions, making the view-to-lead CVR look like 0.7% when the real
--   click-to-lead CVR was ~2.1%.
--
--   Right fix is per-session dedup. Variant-router (Netlify Edge Function)
--   generates a UUID per browser session and stores it in a first-party cookie,
--   gated on Cookiebot statistics consent. log-page-view UPSERTs on
--   (experiment_id, page_slug, session_id) instead of INSERTing, so refreshes
--   and back-button revisits don't multiply. Non-consenting visitors still log
--   loads with NULL session_id (counted as raw loads but excluded from unique
--   denominator). Owner exclusion handled separately by variant-router skipping
--   the beacon entirely when sw_is_owner=true is in the incoming cookie.
--
--   This migration ships the schema half: nullable session_id column, partial
--   unique index, and a new RPC v2 returning both total_loads + unique_sessions
--   per (experiment_id, variant). v1 stays available for any external caller
--   (none today) and continues to return total loads. admin/experiments swaps
--   to v2 in the same commit.
--
-- Related:
--   0068_page_views.sql                    (table created)
--   0159_experiment_view_counts_rpc.sql    (v1 RPC, supersedes the raw SELECT)
--   variant-router.ts                      (cookie + consent + session logic)
--   log-page-view/index.ts                 (UPSERT path)
--   /admin/experiments/page.tsx            (consumer, swapped to v2 same session)
--
-- Impact assessment (per .claude/rules/data-infrastructure.md §8):
--   1. Change: nullable TEXT column added to ads_switchable.page_views;
--      partial unique index added (covers session-deduped UPSERT); new RPC
--      ads_switchable.get_experiment_view_counts_v2. No data migration on
--      existing rows (their session_id stays NULL, contributing to total_loads
--      but not unique_sessions — accurate, since we have no way to know
--      retroactively what session those loads belonged to).
--   2. Readers: /admin/experiments swaps to v2 RPC same commit. v1 RPC kept
--      live (no breaking change). readonly_analytics keeps direct SELECT.
--   3. Writers: log-page-view EF updated same session to include session_id
--      in the INSERT (UPSERT via ON CONFLICT DO NOTHING on the partial index).
--      Other writers: none.
--   4. Schema_version: page_views is internal (no external producer contract).
--      No bump required.
--   5. Data migration: none. Historic rows keep NULL session_id and remain
--      visible in total_loads but contribute zero to unique_sessions. The
--      cutover is forward-looking — dashboard's unique_sessions column grows
--      meaningfully from the cutover date forward.
--   6. Role / policy: none. v2 RPC mirrors v1's SECURITY DEFINER + admin gate
--      + EXECUTE grants to authenticated + readonly_analytics.
--   7. Rollback: DROP RPC v2, DROP INDEX, DROP COLUMN session_id in DOWN.
--      Admin page must revert to v1 if rolled back. Safe at any point.
--   8. Sign-off: owner 2026-05-23.

BEGIN;

-- 1. Column ------------------------------------------------------------------

ALTER TABLE ads_switchable.page_views
  ADD COLUMN session_id TEXT;

COMMENT ON COLUMN ads_switchable.page_views.session_id IS
  'Per-browser-session UUID generated by variant-router.ts. Used by '
  'log-page-view to UPSERT on (experiment_id, page_slug, session_id) so '
  'refreshes/back-button revisits dedup to one row per session. NULL on '
  'visitors without Cookiebot statistics consent (those rows count as raw '
  'loads but not unique sessions) and on all rows pre-2026-05-23. The owner '
  'sw_is_owner cookie short-circuits variant-router so no row is written at '
  'all in that case.';

-- 2. Partial unique index ----------------------------------------------------
-- Covers the ON CONFLICT DO NOTHING path in log-page-view. NULL session_ids
-- bypass the constraint (multiple NULL rows allowed — they're already
-- aggregate-only) while consented visitors get exactly one row per session
-- per experiment+page+variant tuple. Variant included so a visitor whose
-- cookie somehow flips A↔B mid-session would still get a fresh row, though
-- that path shouldn't fire in practice (exp_<id> cookie is 1-year sticky).

CREATE UNIQUE INDEX ads_switchable_page_views_session_unique
  ON ads_switchable.page_views (experiment_id, page_slug, variant, session_id)
  WHERE session_id IS NOT NULL;

-- 3. RPC v2 ------------------------------------------------------------------

CREATE OR REPLACE FUNCTION ads_switchable.get_experiment_view_counts_v2()
RETURNS TABLE(
  experiment_id   TEXT,
  variant         TEXT,
  total_loads     BIGINT,
  unique_sessions BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ads_switchable, admin, public
AS $$
BEGIN
  IF NOT admin.is_admin() THEN
    RAISE EXCEPTION 'Not authorised' USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    pv.experiment_id,
    pv.variant,
    COUNT(*)::BIGINT                                              AS total_loads,
    COUNT(DISTINCT pv.session_id)
      FILTER (WHERE pv.session_id IS NOT NULL)::BIGINT            AS unique_sessions
  FROM ads_switchable.page_views pv
  GROUP BY pv.experiment_id, pv.variant;
END;
$$;

COMMENT ON FUNCTION ads_switchable.get_experiment_view_counts_v2() IS
  'Aggregated A/B page-view stats for /admin/experiments. Returns one row per '
  '(experiment_id, variant) with both total_loads (every row) and '
  'unique_sessions (COUNT DISTINCT session_id, excluding NULLs from '
  'non-consenting visitors and pre-cutover rows). unique_sessions is the '
  'right denominator for conversion-rate display; total_loads is kept for '
  'forensic debugging. SECURITY DEFINER + admin.is_admin() gate; raises 42501 '
  'for non-admin callers. Versioned (_v2) per data-infrastructure.md §12. '
  'Added migration 0162. v1 kept live for any external caller.';

GRANT EXECUTE ON FUNCTION ads_switchable.get_experiment_view_counts_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION ads_switchable.get_experiment_view_counts_v2() TO readonly_analytics;

COMMIT;

-- =============================================================================
-- DOWN
-- =============================================================================
-- BEGIN;
-- DROP FUNCTION IF EXISTS ads_switchable.get_experiment_view_counts_v2();
-- DROP INDEX  IF EXISTS ads_switchable.ads_switchable_page_views_session_unique;
-- ALTER TABLE ads_switchable.page_views DROP COLUMN IF EXISTS session_id;
-- COMMIT;
